import Header from'./Header'
import Footer from './Footer'
import Banner from './Banner'
import Homepage from '../../pages/Shop/Homepage'
import Category from './Category'
import Cart from '../../pages/Shop/Cart'
import Order from './Order'
import CustomerSignUp from '../../pages/Shop/CustomerSignUp'
import CustomerLogin from '../../pages/Shop/CustomerLogin'
import ProductCard from './ProductCard'
import Checkout from '../../pages/Shop/Checkout'
import UpdatePassword from '../../pages/Shop/UpdatePassword'
import Account from '../../pages/Shop/Account'
import AccountContent from '../../pages/Shop/AccountContent'
import OrderPage from '../../pages/Shop/OrderPage'

export { Header, Footer, Banner, Homepage, ProductCard, CustomerSignUp, CustomerLogin, Category, Cart, Order, OrderPage, AccountContent, UpdatePassword, Checkout, Account }